CREATE TABLE player (
ID INT PRIMARY KEY,
COINS INT,
ELO INT,
EMAIL VARCHAR(255),
LOSSES INT,
PASSWORD VARCHAR(255),
USERNAME VARCHAR(255),
WINS INT
);



CREATE TABLE BATTLE_POKEMON (
ID INT PRIMARY KEY,
ATTACK INT,
DAMAGE_DONE INT,
DEFENSE INT,
DOUBLE_DAMAGE VARCHAR(255),
HALF_DAMAGE VARCHAR(255),
HAS_TURN BOOLEAN,
IMAGE VARCHAR(255),
MAX_HP INT,
NAME VARCHAR(255),
POWER_LEVEL INT,
SPEED INT,
TYPES VARCHAR(255),
PLAYER_ID INT,
FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER(ID)
);

CREATE TABLE STARTERS (
    ID INT PRIMARY KEY,
    BATTLE_POKEMON1_ID INT,
    BATTLE_POKEMON2_ID INT,
    BATTLE_POKEMON3_ID INT,
    PLAYER_ID INT,
    CONSTRAINT fk_starter_pokemon1 FOREIGN KEY (BATTLE_POKEMON1_ID) REFERENCES BATTLE_POKEMON(ID),
    CONSTRAINT fk_starter_pokemon2 FOREIGN KEY (BATTLE_POKEMON2_ID) REFERENCES BATTLE_POKEMON(ID),
    CONSTRAINT fk_starter_pokemon3 FOREIGN KEY (BATTLE_POKEMON3_ID) REFERENCES BATTLE_POKEMON(ID),
    CONSTRAINT fk_starter_player FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER(ID)
);